### ISSUE TITLE
manifest for gocd/gocd-agent-ubuntu-16.04:latest not found

### ISSUE THREAD

**Issue by bijookha** [gocd/docker-gocd-agent#10]
When I execute
> $ docker run gocd/gocd-agent-ubuntu-16.04

It gives me the error:

> Unable to find image 'gocd/gocd-agent-ubuntu-16.04:latest' locally
> docker: Error response from daemon: manifest for gocd/gocd-agent-ubuntu-16.04:latest not found.

Even though https://store.docker.com/community/images/gocd/gocd-agent-ubuntu-16.04 exists. What can be problem? Any help/guidance will be greatly appreciated.

Regards

**Comment by varshavaradarajan** [comment]
@bijookha , we do not have the latest tag. try doing `docker run gocd/gocd-agent-ubuntu-16.04:v17.3.0`

**Comment by bijookha** [comment]
Works. Thanks a lot.

**Comment by arvindsv** [comment]
Since we're going to be closing a lot of issues as a duplicate of this, I thought it might be useful to have some commentary about why not just create the 'latest' tag. Some of these posts might be useful to leave here:

http://container-solutions.com/docker-latest-confusion/
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
http://blog.arungupta.me/docker-container-anti-patterns/
