### ISSUE TITLE
Make /var/go the home directory

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/docker-gocd-agent#18]
For installations of the gocd which creates the 'go' user, `/var/go` is the home directory. For consistency's sake, we need to make `/var/go` the home directory within the container as well. 

To avoid breaking the usages of `/home/go`, we can sym link `/home/go` to `/var/go` and add a deprecation notice and remove `/home/go` in a few releases time.

**Comment by ketan** [comment]
Symlinks can get messy with volume mounts. It might be better to keep `/home/go` the home and symlink `/var/go` to `/home/go` if that's really desirable.

**Comment by varshavaradarajan** [comment]
At what point will we get rid of `/home/go` then?

**Comment by ketan** [comment]
`/var/go` is a side-effect of having installed from an installer.

If the point is to provide backward compatability from the installers (or old images) we'd probably want to keep the current (simplified, IMO) structure and symlink `/var/lib/go-server` and `/var/go` into `/godata` and `/home/go`.

**Comment by jyotisingh** [comment]
One of the reasons for /var/go instead of/home/go would be consistency so that we do not have to keep clarifying to the users with things such as - if using Ubuntu with our docker image the this folder or if Ubuntu with regular installer use the other.  Having said that, given the images are already live with/home/go, it does complicate things a bit if we change it now

**Comment by varshavaradarajan** [comment]
After discussion, we have decided to keep the home directory to be `/home/go`.
