### ISSUE TITLE
GoCD agent doesn't seem to connect / work

### ISSUE THREAD

**Issue by Stono** [gocd/docker-gocd-agent#33]
Hi, 
I'm trying to get my head around your new alpine images, and experiencing some issues.  Maybe one of you could fuze with me for a bit?

The latest issue is I have is that my agent seems to connect, is assigned to an environment, i have a pipeline in the environment, but the job never gets picked up by the agent.

I can't see anything in the gocd-agent or gocd-server logs that gives away any sort of problem, however i'm seeing a bunch of 403 (forbidden) errors in nginx:

```
nginx_1   | 172.24.0.4 - - [27/Jun/2017:17:17:53 +0000] "POST /go/remoting/remoteBuildRepository HTTP/1.1" 403 463 "-" "Apache-HttpClient/4.5.2 (Java/1.8.0_121)" "-"
```

I'm guessing the agent (which self registered fine), for whatever reason, can't pull jobs.

I only see those 403s after "enabling" the agent though the GUI, as initially, it is in a pending state.

**Comment by Stono** [comment]
I've replicated the behaviour in docker for you.
Please see https://github.com/Stono/gocd-agent-dind 

Clone it, and do `docker-compose up -d`, wait a minute for the gocd server to boot, then go to https://127.0.0.1 

You'll have a gocd server with a self-registered agent in the pending state.  Enable it, add an environment called docker, create a pipeline in that environment, add an arbitrary task, and you'll see it never runs.

If you do docker-compose logs nginx, you'll see the 403s after enabling the agent.

**Comment by varshavaradarajan** [comment]
I see that there is an `autoregister.properties` file with resources and environment set. But you have to manually enable the agent (it does not **autoregister** itself with the server because the autoregister key is wrong ). Once you do that manually, the autoregister environment is not set on the agent. However, you end up creating a pipeline in an environment. Environment is a grouping of pipelines and agents. The pipelines in an environment can only be run by agents in that environment. Since, your agent (which you manually enabled) is not in the same environment as your pipeline, it won't pick up the job.

**Comment by varshavaradarajan** [comment]
By the way, did docker compose like you instructed, it starts the server, agent and nginx containers, but I can't access the dashboard on https://127.0.0.1 , so can't be sure about the 403s

**Comment by varshavaradarajan** [comment]
Nevermind. It was only a timing issue. The server was up, the agent was in pending state. Added the pipeline and agent to the environment.

**Comment by varshavaradarajan** [comment]
The agents must bypass the proxy - https://docs.gocd.org/current/installation/configure_proxy.html#agents-and-custom-ssl-ports

**Comment by Stono** [comment]
@varshavaradarajan bypassing the proxy worked.  Ta
